### POST REQUEST
POST http://localhost:4004/apiNode/massProducts
Content-Type: application/json

{
	"value": [
        {
			"productName": "Camisa",
			"supplier_ID": 2,
			"category_ID": 6,
			"quantityPerUnit": "12 por pack",
			"unitPrice": 999.99,
			"unitsInStock": 63,
			"unitsOnOrder": 200,
			"reorderLevel": 1,
			"discontinued": false
		},
		{
			"productName": "Falda",
			"supplier_ID": 2,
			"category_ID": 6,
			"quantityPerUnit": "12 por pack",
			"unitPrice": 999.99,
			"unitsInStock": 63,
			"unitsOnOrder": 200,
			"reorderLevel": 1,
			"discontinued": true
		}
	]
}